version: "3.6"

services:
  db:
    hostname: drawing-app
    container_name: drawing_app_database
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: development
    volumes:
      - ./volumes/drawing_app_database/data:/var/lib/postgresql/data
